/**
 * Insight entities — AI reflection types for UnSaid.
 *
 * This file is the canonical source of truth for all AI configuration
 * and type definitions on the client. Provider-specific logic is isolated
 * inside Edge Functions; nothing here references HuggingFace or any
 * other provider by name.
 */

// ─── AI Configuration ────────────────────────────────────────

/**
 * Canonical AI configuration for UnSaid.
 *
 * promptVersion: bump this string whenever the per-entry reflection prompt
 *   changes in either Edge Function. All existing per-entry source_hash values
 *   become stale — users see "Re-reflect" on their next visit. This is
 *   intentional: the new version supersedes all prior cached output.
 *
 *   History: 1.0.0 → 2.0.0 (reflection overhaul), 2.0.0 → 2.1.0 (voice fix)
 *
 * defaultModel: fallback display value if the user has not set a model in
 *   settings. The actual model used at inference time comes from
 *   settings.aiModel (mapped from user_settings.hf_model in the DB).
 *
 * EDGE FUNCTION NOTE: supabase/functions/analyze-sentiment/index.ts and
 *   supabase/functions/generate-reflection/index.ts each contain a local
 *   AI_CONFIG mirror. Keep all three in sync when bumping promptVersion
 *   and redeploying the functions.
 */
export const AI_CONFIG = {
  promptVersion: '2.1.0',
  defaultModel: 'j-hartmann/emotion-english-distilroberta-base',
} as const;

// ─── Insight types ────────────────────────────────────────────

/**
 * InsightType — extensible union, no schema change required to add new types.
 * The `type` column CHECK constraint already covers all four values.
 * Adding a new AI capability requires:
 *   1. A new Supabase Edge Function (supabase/functions/<capability>/index.ts)
 *   2. Adding the new type to this union
 *   3. Adding a new AiAction entry in JournalEditor with enabled: true
 */
export type InsightType = 'sentiment' | 'summary' | 'pattern' | 'reflection';

/**
 * Stored inside every insight payload as payload._meta.
 * Makes each DB row self-describing — no joins required to understand
 * how or when an insight was generated, or with which provider/model/prompt.
 */
export interface InsightMeta {
  /**
   * Prompt version that generated this insight.
   * Per-entry reflections: "2.1.0" (AI_CONFIG.promptVersion).
   * Weekly reflections: "1.0.0" (WEEKLY_CONFIG.version).
   * Bump the relevant version in the Edge Function to invalidate caches
   * of that type only — the two version spaces are independent.
   */
  version: string;
  /**
   * Inference backend identifier, e.g. "huggingface" or "groq".
   * Stored so rows remain interpretable if additional backends are added later.
   * Added in prompt version 1.0.0; absent on rows generated before this field
   * was introduced (treat missing as "huggingface" for backward compatibility).
   */
  provider: string;
  /** AI model identifier. Provider-specific value, opaque to the client. */
  model: string;
  /** ISO 8601 UTC timestamp of when the insight was generated. */
  generatedAt: string;
  /** Wall-clock milliseconds for the inference call. 0 = cache hit. */
  generationMs: number;
}

/**
 * Full typed payload for type='sentiment'.
 * Stored in the DB; includes _meta for self-description.
 */
export interface SentimentPayload {
  /** Normalised score from -1 (most negative) to 1 (most positive). */
  score: number;
  label: 'negative' | 'neutral' | 'positive';
  /** Confidence of the winning label, 0–1. */
  confidence: number;
  _meta: InsightMeta;
}

/**
 * Edge Function wire return type — what generateInsight() returns to the client.
 * Intentionally excludes _meta: the UI only needs the sentiment result.
 */
export interface SentimentResult {
  score: number;
  label: 'negative' | 'neutral' | 'positive';
  confidence: number;
}

// ─── Reflection types ─────────────────────────────────────────

/**
 * A single emotion in a reflection payload — top-4 by score from HF model.
 */
export interface ReflectionEmotion {
  /** Human-readable capitalised label, e.g. "Joy", "Sadness". */
  label: string;
  /** Probability score 0–1 from the HF model. */
  score: number;
}

/**
 * Full typed payload for type='reflection'.
 * Stored in the DB; includes _meta for self-description.
 * _meta.provider = 'groq' for all reflection rows.
 */
export interface ReflectionPayload {
  /** 2–3 sentence reflection generated by Groq. */
  summary: string;
  /** Top 4 emotions by score from the HF emotion model. */
  emotions: ReflectionEmotion[];
  /** 1–3 detected topics from the journal entry. */
  themes: string[];
  /** One open-ended follow-up question to encourage deeper journaling. */
  question: string;
  _meta: InsightMeta;
}

/**
 * Edge Function wire return type — what generateReflection() returns to the client.
 * Identical to ReflectionPayload minus _meta.
 */
export interface ReflectionResult {
  summary: string;
  emotions: ReflectionEmotion[];
  themes: string[];
  question: string;
}

// ─── Weekly summary types ─────────────────────────────────────

/**
 * Full typed payload for type='summary' rows (weekly reflection).
 * Stored in the DB; includes _meta for self-description.
 * _meta.weeklyPromptVersion tracks the weekly prompt version independently
 * from the per-entry promptVersion so that per-entry caches are never
 * invalidated by changes to the weekly synthesis prompt.
 */
export interface WeeklyPayload {
  /** 2–4 sentence narrative synthesising the week's emotional arc. */
  narrative: string;
  /** Top emotions aggregated across the week's entries, sorted by score desc. */
  dominantEmotions: ReflectionEmotion[];
  /** Recurring themes detected across the week, deduplicated. */
  recurringThemes: string[];
  /** Short phrase describing the emotional trajectory, e.g. "from uncertainty toward calm". */
  emotionalArc: string;
  _meta: InsightMeta;
}

/**
 * Edge Function wire return type — what generateWeeklySummary() returns to the client.
 * Identical to WeeklyPayload minus _meta.
 */
export interface WeeklyResult {
  narrative: string;
  dominantEmotions: ReflectionEmotion[];
  recurringThemes: string[];
  emotionalArc: string;
}

/**
 * Type-narrowing guard: returns true if p contains WeeklyPayload fields.
 * Checks structural shape only — does not require _meta.
 */
export function isWeeklyPayload(p: unknown): p is WeeklyPayload {
  if (typeof p !== 'object' || p === null) return false;
  const v = p as Record<string, unknown>;
  return (
    typeof v.narrative === 'string' && v.narrative.trim().length > 0 &&
    Array.isArray(v.dominantEmotions) &&
    Array.isArray(v.recurringThemes) &&
    typeof v.emotionalArc === 'string'
  );
}

/**
 * A typed insight row read from the DB via insightsService.getInsights().
 * The payload field is open-schema (Record<string, unknown>) to accommodate
 * future insight types without requiring code changes here.
 */
export interface EntryInsight {
  id: string;
  /** The journal entry this insight was generated from. Null for user-level insights. */
  entryId: string | null;
  type: InsightType;
  /** Open-schema — use isSentimentPayload(), isReflectionPayload(), or isWeeklyPayload() to narrow. */
  payload: Record<string, unknown>;
  /**
   * SHA-256 of the source envelope at generation time.
   * - Per-entry rows: sha256Hex(sourceEnvelope(content, promptVersion, model))
   * - Weekly rows: sha256Hex(JSON.stringify({ weekStart, weekEnd, weeklyPromptVersion, model, entryHashes }))
   * Null for legacy rows (pre-migration). Null rows are treated as always-stale.
   */
  sourceHash: string | null;
  createdAt: string;
  /**
   * ISO date string ("YYYY-MM-DD") for the start of the period this insight covers.
   * Null for per-entry insights (type='reflection' or 'sentiment').
   * Set for period insights (type='summary' or 'pattern').
   */
  periodStart: string | null;
  /**
   * ISO date string ("YYYY-MM-DD") for the end of the period this insight covers.
   * Null for per-entry insights (type='reflection' or 'sentiment').
   * Set for period insights (type='summary' or 'pattern').
   */
  periodEnd: string | null;
}

/**
 * Type-narrowing guard: returns true if p contains SentimentPayload fields.
 * Parameter is `unknown` — widest safe type for a type guard — so it works
 * for both payload.score === 'number' checks and TypeScript's predicate constraint.
 * Checks only the core result fields; _meta may be absent on legacy rows.
 */
export function isSentimentPayload(p: unknown): p is SentimentPayload {
  if (typeof p !== 'object' || p === null) return false;
  const v = p as Record<string, unknown>;
  return (
    typeof v.score === 'number' &&
    typeof v.label === 'string' &&
    typeof v.confidence === 'number'
  );
}

/**
 * Type-narrowing guard: returns true if p contains ReflectionPayload fields.
 * Checks structural shape only — does not require _meta (absent on wire results).
 */
export function isReflectionPayload(p: unknown): p is ReflectionPayload {
  if (typeof p !== 'object' || p === null) return false;
  const v = p as Record<string, unknown>;
  return (
    typeof v.summary === 'string' &&
    Array.isArray(v.emotions) &&
    v.emotions.length > 0 &&
    Array.isArray(v.themes) &&
    typeof v.question === 'string'
  );
}

/**
 * A single item in the "Reflect" AI menu (AiMenu component).
 *
 * v2 registered actions:
 *   { id: 'generate-insight', label: 'Reflect',           enabled: true }
 *   { id: 'summarize-entry',  label: 'Summarize Entry',   enabled: false, disabledReason: 'Coming soon' }
 *   { id: 'reflection-prompt',label: 'Reflection Prompt', enabled: false, disabledReason: 'Coming soon' }
 *   { id: 'find-patterns',    label: 'Find Patterns',     enabled: false, disabledReason: 'Coming soon' }
 *
 * To activate a new capability in a future version:
 *   1. Add its Edge Function to supabase/functions/
 *   2. Add the type to InsightType (if new)
 *   3. Flip enabled: true on the corresponding AiAction in JournalEditor
 *   No changes to AiMenu, JournalEditor layout, or the trigger button are needed.
 */
export interface AiAction {
  /** Stable identifier, e.g. 'generate-insight'. */
  id: string;
  /** Display label in the menu, e.g. 'Reflect'. */
  label: string;
  /** Optional one-line description shown below the label. */
  description?: string;
  /** Which insight type this action produces. */
  insightType: InsightType;
  /** Called when the user selects this action from the menu. */
  invoke: () => void;
  /** If false, the item is rendered disabled with disabledReason subtext. */
  enabled: boolean;
  /** Shown below the label when enabled is false, e.g. 'Coming soon'. */
  disabledReason?: string;
}

// ─── Memory + Heatmap (unchanged from original) ──────────────

export interface Memory {
  id: string;
  entryDate: string;
  snippet: string;
  mood: string | null;
  daysAgo: number;
}

export interface HeatmapCell {
  date: string; // "YYYY-MM-DD"
  count: number; // 0 or 1 for journaling (entry exists or not)
  mood: string | null;
}
